// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/olusolaa/infra-drift-detector/internal/core/ports"
	mock "github.com/stretchr/testify/mock"
)

// RateLimiter is an autogenerated mock type for the RateLimiter type
type RateLimiter struct {
	mock.Mock
}

// Wait provides a mock function with given fields: ctx, logger
func (_m *RateLimiter) Wait(ctx context.Context, logger ports.Logger) error {
	ret := _m.Called(ctx, logger)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.Logger) error); ok {
		r0 = rf(ctx, logger)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRateLimiter creates a new instance of RateLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRateLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *RateLimiter {
	mock := &RateLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
