settings:
  log_level: info
  log_format: text
  concurrency: 5
  colored_output: true

state:
  provider_type: tfstate
  tfstate:
    path: ./terraform.tfstate

platform:
  provider: aws
  aws:
    region: "eu-west-1"
    use_shared_credentials: false
    profile: "default"  # Added back as it's required by config validation

matching:
  strategy: tag
  tag:
    key: "TFResourceAddress"

normalization:
  attributes:
    - name: security_groups
      strategy: extract_id

resources:
  - kind: ComputeInstance
    attributes:
      - instance_type
      - tags
      - disable_api_termination
  - kind: StorageBucket
    attributes:
      - tags
      - versioning
      - objects
