// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/olusolaa/infra-drift-detector/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// StateProvider is an autogenerated mock type for the StateProvider type
type StateProvider struct {
	mock.Mock
}

// GetResource provides a mock function with given fields: ctx, kind, identifier
func (_m *StateProvider) GetResource(ctx context.Context, kind domain.ResourceKind, identifier string) (domain.StateResource, error) {
	ret := _m.Called(ctx, kind, identifier)

	if len(ret) == 0 {
		panic("no return value specified for GetResource")
	}

	var r0 domain.StateResource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ResourceKind, string) (domain.StateResource, error)); ok {
		return rf(ctx, kind, identifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ResourceKind, string) domain.StateResource); ok {
		r0 = rf(ctx, kind, identifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.StateResource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ResourceKind, string) error); ok {
		r1 = rf(ctx, kind, identifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListResources provides a mock function with given fields: ctx, kind
func (_m *StateProvider) ListResources(ctx context.Context, kind domain.ResourceKind) ([]domain.StateResource, error) {
	ret := _m.Called(ctx, kind)

	if len(ret) == 0 {
		panic("no return value specified for ListResources")
	}

	var r0 []domain.StateResource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ResourceKind) ([]domain.StateResource, error)); ok {
		return rf(ctx, kind)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ResourceKind) []domain.StateResource); ok {
		r0 = rf(ctx, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StateResource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ResourceKind) error); ok {
		r1 = rf(ctx, kind)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Type provides a mock function with no fields
func (_m *StateProvider) Type() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewStateProvider creates a new instance of StateProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateProvider {
	mock := &StateProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
